/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tuitionmanagement;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javafx.scene.input.KeyCode;
import javax.swing.JLabel;

/**
 *
 * @author irvin
 */
public class LoginFrame extends javax.swing.JFrame {

    private int relativeX = -1, relativeY = -1; 
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        loginButton.grabFocus();
        setLocationRelativeTo(null);
    }

    private void initiateLoginSequence() {
        String user = usernameTextField.getText();
        String pass = jPasswordField.getText();
        if (user.equals("root") && pass.equals("root")) {
            this.setVisible(false);
            MainFrame.createAndShowGUI();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        leftLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setName("leftPanel"); // NOI18N
        leftPanel.setPreferredSize(new java.awt.Dimension(300, 400));

        leftLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/TuitionManagement.jpg"))); // NOI18N
        leftLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveWindowMouseDragged(evt);
            }
        });
        leftLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveWindowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moveWindowMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setForeground(new java.awt.Color(54, 169, 112));
        rightPanel.setFocusCycleRoot(true);
        rightPanel.setMinimumSize(new java.awt.Dimension(300, 400));
        rightPanel.setPreferredSize(new java.awt.Dimension(300, 400));
        rightPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveWindowMouseDragged(evt);
            }
        });
        rightPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveWindowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                moveWindowMouseReleased(evt);
            }
        });
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameTextField.setForeground(java.awt.Color.lightGray);
        usernameTextField.setText("Username");
        usernameTextField.setBorder(null);
        usernameTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        usernameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFieldFocusLost(evt);
            }
        });
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        rightPanel.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 146, -1, -1));

        passwordTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordTextField.setForeground(java.awt.Color.lightGray);
        passwordTextField.setText("Password");
        passwordTextField.setBorder(null);
        passwordTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        passwordTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTextFieldFocusGained(evt);
            }
        });
        rightPanel.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 202, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        rightPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 175, -1, -1));

        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        rightPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 232, -1, -1));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 204, 204));
        titleLabel.setText("Hello, coach!");
        titleLabel.setToolTipText("");
        rightPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 90, -1, -1));

        loginButton.setBackground(new java.awt.Color(0, 204, 204));
        loginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButton.setText("LOGIN");
        loginButton.setOpaque(true);
        loginButton.setPreferredSize(new java.awt.Dimension(200, 30));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        rightPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 260, -1, -1));

        closeButton.setBackground(new java.awt.Color(255, 255, 255));
        closeButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8_Multiply_25px_1.png"))); // NOI18N
        closeButton.setOpaque(true);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeButtonMouseReleased(evt);
            }
        });
        rightPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, -1));

        jPasswordField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPasswordField.setBorder(null);
        jPasswordField.setPreferredSize(new java.awt.Dimension(200, 30));
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        rightPanel.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 202, -1, -1));

        getContentPane().add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // BEGIN - loginButton Events
    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setBackground(new Color(0,204,204).darker());
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        loginButton.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_loginButtonMouseExited
    // END - loginButton Events
    
    private void moveWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveWindowMousePressed
        relativeX = evt.getX();
        relativeY = evt.getY();
        if (evt.getSource() == rightPanel)
            relativeX += leftPanel.getWidth();
    }//GEN-LAST:event_moveWindowMousePressed

    private void moveWindowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveWindowMouseReleased
        relativeX = -1;
        relativeY = -1;
    }//GEN-LAST:event_moveWindowMouseReleased

    private void moveWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveWindowMouseDragged
        if (relativeX == -1 || relativeY == -1) return;
        this.setLocation(
                evt.getXOnScreen()-relativeX, 
                evt.getYOnScreen()-relativeY
        );
    }//GEN-LAST:event_moveWindowMouseDragged
    // END - moveWindow Events
    
    
    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        closeButton.setBackground(Color.WHITE);
    }//GEN-LAST:event_closeButtonMouseExited

    private void closeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMousePressed
        closeButton.setBackground(Color.RED.darker());
    }//GEN-LAST:event_closeButtonMousePressed

    private void closeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseReleased
        if (0 <= evt.getX() && evt.getX() <= ((JLabel)evt.getSource()).getWidth() &&
                0 <= evt.getY() && evt.getY() <= ((JLabel)evt.getSource()).getHeight()) 
            System.exit(0);
    }//GEN-LAST:event_closeButtonMouseReleased

    private void usernameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusGained
        if (usernameTextField.getText().equals("Username")) {
            usernameTextField.setForeground(Color.BLACK);
            usernameTextField.setText("");
        }
    }//GEN-LAST:event_usernameTextFieldFocusGained

    private void usernameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFieldFocusLost
        if (usernameTextField.getText().length() == 0) {
            usernameTextField.setForeground(Color.LIGHT_GRAY);
            usernameTextField.setText("Username");
        }
    }//GEN-LAST:event_usernameTextFieldFocusLost

    private void passwordTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFieldFocusGained
        if (jPasswordField.getText().length() == 0) {
            passwordTextField.setVisible(false);
            jPasswordField.setVisible(true);
            jPasswordField.grabFocus();
        }
    }//GEN-LAST:event_passwordTextFieldFocusGained

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        initiateLoginSequence();
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        initiateLoginSequence();
    }//GEN-LAST:event_loginButtonMouseClicked

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        initiateLoginSequence();
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        if (jPasswordField.getText().length() == 0) { //passwordField still empty
            jPasswordField.setVisible(false);
            passwordTextField.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel leftLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel loginButton;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
