/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tuitionmanagement;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author irvin
 */
public class MainFrame extends javax.swing.JFrame {

    private int relativeX = -1;
    private int relativeY = -1;
    private JPanel[] sidePanels;
    private JPanel selectedSidePanel;
    private List<String> sideButtonNames;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        selectedSidePanel = homeButton;
        sidePanels = new JPanel[] {
            homeButton,
            dataButton
        };
        sideButtonNames = new ArrayList<String>();
        for (JPanel panel : sidePanels)
            sideButtonNames.add(panel.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dataButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowPanel.setBackground(new java.awt.Color(51, 51, 51));
        windowPanel.setPreferredSize(new java.awt.Dimension(750, 30));
        windowPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                windowPanelMouseDragged(evt);
            }
        });
        windowPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                windowPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                windowPanelMouseReleased(evt);
            }
        });
        windowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-graduation-cap-25.png"))); // NOI18N
        logoLabel.setText("jLabel1");
        logoLabel.setPreferredSize(new java.awt.Dimension(25, 25));
        windowPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 3, -1, -1));

        closeButton.setBackground(new java.awt.Color(0, 51, 51));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-delete-30.png"))); // NOI18N
        closeButton.setText("jLabel2");
        closeButton.setOpaque(true);
        closeButton.setPreferredSize(new java.awt.Dimension(30, 30));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeButtonMouseReleased(evt);
            }
        });
        windowPanel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        minimizeButton.setBackground(new java.awt.Color(0, 51, 51));
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-horizontal-line-30.png"))); // NOI18N
        minimizeButton.setOpaque(true);
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseReleased(evt);
            }
        });
        windowPanel.add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Tuition Management");
        windowPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 7, -1, -1));

        getContentPane().add(windowPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sidePanel.setBackground(new java.awt.Color(0, 51, 51));
        sidePanel.setPreferredSize(new java.awt.Dimension(100, 470));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setBackground(new java.awt.Color(0, 204, 204));
        homeButton.setMinimumSize(new java.awt.Dimension(100, 100));
        homeButton.setPreferredSize(new java.awt.Dimension(100, 100));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sideMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sideMenuMouseExited(evt);
            }
        });
        homeButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-home-50.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 50));
        homeButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HOME");
        homeButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 70, -1, -1));

        sidePanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        dataButton.setBackground(new java.awt.Color(0, 51, 51));
        dataButton.setName("dataButton"); // NOI18N
        dataButton.setPreferredSize(new java.awt.Dimension(100, 100));
        dataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sideMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sideMenuMouseExited(evt);
            }
        });
        dataButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-database-administrator-50.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 50));
        dataButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 20, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA");
        dataButton.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 75, -1, -1));

        sidePanel.add(dataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPane.setMaximumSize(new java.awt.Dimension(1000, 1000));
        tabbedPane.setMinimumSize(new java.awt.Dimension(650, 470));
        tabbedPane.setPreferredSize(new java.awt.Dimension(650, 470));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setMaximumSize(new java.awt.Dimension(650, 470));
        homePanel.setMinimumSize(new java.awt.Dimension(650, 470));
        homePanel.setPreferredSize(new java.awt.Dimension(650, 470));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-checkmark-120.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 120));
        homePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("\"Look at the mirror. That's your competition.\"");
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 490, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/homePhoto.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel7.setMinimumSize(new java.awt.Dimension(650, 470));
        jLabel7.setPreferredSize(new java.awt.Dimension(650, 470));
        jLabel7.setRequestFocusEnabled(false);
        homePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        tabbedPane.addTab("tab1", homePanel);

        dataPanel.setBackground(new java.awt.Color(255, 255, 255));
        dataPanel.setMaximumSize(new java.awt.Dimension(650, 470));
        dataPanel.setMinimumSize(new java.awt.Dimension(650, 470));
        dataPanel.setPreferredSize(new java.awt.Dimension(650, 470));

        jLabel6.setText("jLabel6");
        jLabel6.setName("homeButton"); // NOI18N
        dataPanel.add(jLabel6);

        tabbedPane.addTab("tab2", dataPanel);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 5, 650, 495));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseEntered
        minimizeButton.setBackground(Color.decode("#333333").brighter()); 
    }//GEN-LAST:event_minimizeButtonMouseEntered

    private void minimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseExited
        minimizeButton.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_minimizeButtonMouseExited

    private void minimizeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseReleased
        if (0 <= evt.getX() && evt.getX() <= ((JLabel)evt.getSource()).getWidth() &&
                0 <= evt.getY() && evt.getY() <= ((JLabel)evt.getSource()).getHeight())  
            this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseReleased

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        closeButton.setBackground(Color.RED); 
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        closeButton.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_closeButtonMouseExited

    private void closeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseReleased
        if (0 <= evt.getX() && evt.getX() <= ((JLabel)evt.getSource()).getWidth() &&
                0 <= evt.getY() && evt.getY() <= ((JLabel)evt.getSource()).getHeight())  
            System.exit(0);
    }//GEN-LAST:event_closeButtonMouseReleased

    private void windowPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowPanelMousePressed
        relativeX = evt.getX();
        relativeY = evt.getY();
    }//GEN-LAST:event_windowPanelMousePressed

    private void windowPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowPanelMouseReleased
        relativeX = -1;
        relativeY = -1;
    }//GEN-LAST:event_windowPanelMouseReleased

    private void windowPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_windowPanelMouseDragged
        this.setLocation(evt.getXOnScreen()-relativeX, evt.getYOnScreen()-relativeY);
    }//GEN-LAST:event_windowPanelMouseDragged

    private void sideMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuMouseEntered
        JPanel curPanel = (JPanel)evt.getSource();
        if (selectedSidePanel == curPanel) return;
        curPanel.setBackground(Color.decode("#333333").brighter());
    }//GEN-LAST:event_sideMenuMouseEntered

    private void sideMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuMouseExited
        JPanel curPanel = (JPanel)evt.getSource();
        if (selectedSidePanel == curPanel) return;
        curPanel.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_sideMenuMouseExited

    private void sideMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuMouseClicked
        for (JPanel panel : sidePanels)
            panel.setBackground(Color.decode("#333333"));
        //update current selected sidePanel
        JPanel curPanel = (JPanel)evt.getSource();
        selectedSidePanel = curPanel;
        curPanel.setBackground(Color.decode("#00cccc"));
        tabbedPane.setSelectedIndex(sideButtonNames.indexOf(curPanel.getName()));
    }//GEN-LAST:event_sideMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        createAndShowGUI();
    }

    public static void createAndShowGUI() {
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel dataButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel windowPanel;
    // End of variables declaration//GEN-END:variables
}
